name: build-exe

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  win-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build exe
        shell: cmd
        run: |
          pyinstaller --onefile --windowed ^
            --hidden-import telethon ^
            --hidden-import pyaes ^
            --hidden-import rsa ^
            gui_pdf_downloader.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-pdf-downloader-${{ github.run_number }}-win
          path: dist/*.exe
